name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the Next.js app (static export)
      - name: Build Next.js app
        run: |
          npm run build
          npm run export  # Ensure you have a script to export to the 'out' folder

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (usually 'gh-pages')
          folder: out       # The folder containing the built static files
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the action
